#!/bin/bash

cmake -S moab -B moab-build \
    -DENABLE_HDF5=ON \
    -DENABLE_NETCDF=OFF \
    -DBUILD_SHARED_LIBS=ON \
    -DENABLE_FORTRAN=OFF \
    -DENABLE_BLASLAPACK=OFF \
    -DENABLE_PYMOAB=OFF

cmake --build moab-build -j 2 -t install
