name: Release

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # for testing
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: cp311-*
          #   CIBW_ARCHS_MACOSg: "x86_64 arm64"
          CIBW_ARCHS_MACOSg: "arm64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_ALL_LINUX: |
            set -eu
            dnf install -y cmake eigen3-devel gcc gcc-c++ make wget

            HDF5_VERSION="1.14.2"
            wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${HDF5_VERSION}/src/hdf5-${HDF5_VERSION}.tar.gz
            tar -xzvf hdf5-${HDF5_VERSION}.tar.gz
            cd hdf5-${HDF5_VERSION}
            ./configure
            make -j$(nproc)
            make install

            bash build-moab
          CIBW_BEFORE_ALL_MACOS: |
            if [ "$arch" == "arm64" ]; then
                PACKAGES=(eigen hdf5)
                for PACKAGE in "${PACKAGES[@]}"
                do
                    brew fetch --force --bottle-tag=arm64_big_sur $PACKAGE
                    brew install $(brew --cache --bottle-tag=arm64_big_sur $PACKAGE)
                done
            else
                brew install eigen hdf5
            fi
            bash build-moab

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
