name: Release

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macos-11]
        os: [ubuntu-20.04, macos-11, macos-13-xlarge]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BEFORE_ALL_LINUX: yum install cmake hdf5-devel
          CIBW_BEFORE_ALL_MACOS: brew install llvm
          CIBW_ENVIRONMENT_MACOS: CC=/opt/homebrew/opt/llvm/bin/clang CXX=/opt/homebrew/opt/llvm/bin/clang++

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
